### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/dynamic-graph-python#20]
Hi,

This project has been written with `PyCObject`, which has been deprecated in python 2.7 & 3.1, and removed later, so we must switch to the new `Capsules` API.

References:
https://docs.python.org/3/howto/cporting.html#cobject-replaced-with-capsule
https://docs.python.org/3.7/extending/extending.html#providing-a-c-api-for-an-extension-module

**Comment by nim65s** [comment]
But first, I'd like to ask: what was the initial reason to use this `PyCObject`API, instead of `boost::Python`?

**Comment by florent-lamiraux** [comment]
I am the one who took this decision almost 10 years ago. I do not remember the rationale, but at that time I had not been convinced by boost::Python and I found natural to use something called C/Python API for what I was about to do (bind C++ with python).

**Comment by nim65s** [comment]
OK, thanks for your answer.
In this case I think we can just convert those items to `boost::Python`.

I also found a bit of `PyCObject` there: https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/dynamic_graph/python-module-py.cc ; is this still usefull ? And in this case, should we also move this to `boost::Python` ?

**Comment by florent-lamiraux** [comment]
I do not remember.

**Comment by jmirabel** [comment]
Yes, it is important. This file is compile into a "wrap.so", which is loaded when doing "import sot....". it shouldn't be hard to convert it.

**Comment by jmirabel** [comment]
Moreover, if you feel like working on this, there are three levels of shared libraries in SoT: "libsot-core.so", the libraries in "lib/plugins/*.so" and the libraries in lib/python2.7/site-packages/.../wrap.so".

A month ago, I realized this could be updated to have only two levels. This would remove the "plugin" folder". I think it can be achieve only with changes in CMake files.
