### ISSUE TITLE
Python interface for logger verbosity

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/dynamic-graph-python#28]
In C++, it is possible to set an entity's logger verbosity with the method `setLoggerVerbosityLevel(LoggerVerbosity)`. It would be nice to have a Python command for this, in order to be able to set this property easily and dynamically through Python.

**Comment by nim65s** [comment]
https://docs.python.org/3.7/library/logging.html#logging.Handler.setLevel :)

**Comment by gabrielebndn** [comment]
Oh, I didn't know about that, thanks! But I don't manage to make it work.

**Comment by olivier-stasse** [comment]
This issue is related to #41. Therefore I am closing it. Feel free to reopen it if needed.
