### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/dynamic-graph-python#33]
I recommend a new release including the `devel` branch, so that the new policy of `dist-packages` vs `site-packages` is enforced.
`devel` differs from the current release for two commits only, including the `cmake` update and some changes concerning sphinx.
Once the release is made, `master` should be made equal to the release (this is not the case right now).
Together with the new release, it should be checked that the other packages generating Python submodules of `dynamic_graph` also update their `cmake`.

**Comment by gabrielebndn** [comment]
See https://github.com/stack-of-tasks/sot-core/pull/110#issuecomment-546144265 for an example of problems that might arise

**Comment by nim65s** [comment]
A new release would change nothing to this `dist-packages` vs `site-packages`, as this is computed at build time, not at release time.

**Comment by jmirabel** [comment]
> A new release would change nothing to this `dist-packages` vs `site-packages`, as this is computed at build time, not at release time.

The new release will have a different default behavior wrt the previous one so, yes, it does have an effect on `dist-packages` vs `site-packages`

**Comment by gabrielebndn** [comment]
> A new release would change nothing to this `dist-packages` vs `site-packages`, as this is computed at build time, not at release time.

The new release will have Python modules in `dist-packages` instead of `site-packages`, so it will change

**Comment by nim65s** [comment]
Are you talking about a source release or a binary release ?

**Comment by jmirabel** [comment]
I think @gabrielebndn 's issue happens in a situation with a mix of robotpkg binaries and git sources (outside of robotpkg). For the binary release, @nim65s is right, the path won't change.

**Comment by gabrielebndn** [comment]
> I think @gabrielebndn 's issue happens in a situation with a mix of robotpkg binaries and git sources (outside of robotpkg). For the binary release, @nim65s is right, the path won't change.

No, right now I am only on sources. The problems I got [jrl-umi3218/jrl-cmakemodules#234](https://github.com/jrl-umi3218/jrl-cmakemodules/pull/234) are using sources only.

I just want a fixed point: knowing that *all* latest releases install in `dist-packages` by default, so I don not have to worry about it when compiling manually

**Comment by gabrielebndn** [comment]
See #58

**Comment by nim65s** [comment]
Ok, now that I understand your point. This is about having the same defaults everywhere.

Then, can you wait for the next week for this release ? I should be able to make a new release of everything with an up-to-date cmake module everywhere and Python 3 support.

Otherwise, if you are stuck anywhere with the current state, I can help.

**Comment by gabrielebndn** [comment]
> Then, can you wait for the next week for this release ? I should be able to make a new release of everything with an up-to-date cmake module everywhere and Python 3 support.
> 
> Otherwise, if you are stuck anywhere with the current state, I can help.

Next week is perfectly fine, thanks :) I will manage to handle in the meanwhile

**Comment by gabrielebndn** [comment]
> > > Are you talking about a source release or a binary release ?
> > 
> > 
> > I don't see the reason of making a difference. A source release and corresponding binary release I would say
> 
> No, robotpkg follows python policy and not debian policy, so you should never see any `dist-package` in any binary release.

I see, thanks for explaining.
So, it would only impact source builds. What I meant by "no difference" is that once a source release is made I think it should be easy to make the binary releases, since I guess most of the work for making it consistent will be already done because of `dist-packages`. But then, this is for you to judge :)

**Comment by nim65s** [comment]
v3.4.0 is available in source and in binary.

The cmake submodule should have been updated everywhere, so the behavior regarding the site package should be the same everywhere.

Is it OK for you now, @gabrielebndn ?
