### ISSUE TITLE
Add check that `dg.plug` connects two signals

### ISSUE THREAD

**Issue by jviereck** [stack-of-tasks/dynamic-graph-python#36]
When using `dynamic_graph.plug(a, b)`, a common bug is to pass an operator for `a` or `b` instead of a signal. It would be great if the underlying `plug(...)` function asserts the passed in objects derive from `SignalBase`.

Here is a python hack that helped me to track down a plugging bug:

```python
import dynamic_graph as dg
plug_ = dg.plug

# Monkey patch it till you make it.
def dg_plug_dbg(sig0, sig1):
    def assert_signal(sig):
        if not isinstance(sig, dg.signal_base.SignalBase):
            raise ValueError('dynamic_graph.plug(): Passed in value is not a signal. sig=' + str(sig), sig)
    assert_signal(sig0)
    assert_signal(sig1)
    plug_(sig0, sig1)

dg.plug = dg_plug_dbg
```

\cc @MaximilienNaveau

**Comment by jmirabel** [comment]
This will come when porting to Python 3. See https://github.com/stack-of-tasks/dynamic-graph-python/pull/34#discussion_r345792056

**Comment by jviereck** [comment]
Thanks!

**Comment by jviereck** [comment]
One question though: what's the current error message from dg.plug if one
of the signals has the wrong type/is not a signal? The "Something bad
happened" from the unit test is not giving much of an insight what is wrong
and how to fix it.

**Comment by jmirabel** [comment]
You get the error from https://docs.python.org/2/c-api/capsule.html#c.PyCapsule_GetPointer

I guess it is a TypeError but I am not sure.

**Comment by jmirabel** [comment]
I think you get `ValueError: PyCapsule_GetPointer called with incorrect name`, which isn't particularly helpful (still better than a SEGV though).

**Comment by nim65s** [comment]
@jmirabel that's correct.
@jviereck : you read the wrong line in the unit test:
https://github.com/stack-of-tasks/dynamic-graph-python/blob/master/unitTesting/test_bindings.py#L21

**Comment by jviereck** [comment]
Is there a way we can get a better error message when passing a non-signal argument? I agree that the current solution is much better than before. However, at least in my experience this is a common source of bugs / happens very easily and a good error message would therefore be useful.

**Comment by nim65s** [comment]
Sure, I'll give a try
